### ISSUE TITLE
Plugin fails

### ISSUE THREAD

**Issue by EricKramp** [aaroniker/figma-remove-bg#1] opened 2020-02-20 21:08 UTC
Hey, seems like a great plugin, but it keeps failing when we try to use it. I setup the free account and entered my api key, but we're seeing failures on 2 different computers with this same error message.

![error-image](https://user-images.githubusercontent.com/1298131/74978638-e69cbc80-53e1-11ea-8736-7aabdd00c3f4.png)

**Comment by aaroniker** [comment] 2020-02-27 06:50
Hi, thanks for your report!
Sry for the late answer - could you send me the image?
So i can reproduce :)

Greetings,
Aaron

**Comment by EricKramp** [comment] 2020-02-28 00:11
Hey @aaroniker, no worries at all. It's just a photo from unsplash, I don't have a copy of the other image that failed, but here you go: 

![jay-wennington-_CrbZkVXoEY-unsplash](https://user-images.githubusercontent.com/1298131/75498334-b6be5d80-597b-11ea-9547-2c5f459cca1a.jpg)

**Comment by EricKramp** [comment] 2020-02-28 02:45
And for what it's worth, I just tried the same image on the website directly and it works ok there. I can confirm that that behavior is consistent across a couple of images.

<img width="1218" alt="image" src="https://user-images.githubusercontent.com/1298131/75505887-4e7a7680-5991-11ea-9d56-51d9dbdf1f48.png">

**Comment by lucianomilen** [comment] 2020-04-09 14:45
That's happening to me as well, with any image I try.

**Comment by aaroniker** [comment] 2020-04-10 09:42
@lucianomilen thanks for reporting, still looking into this - will try to reproduce at the weekend

**Comment by DennisLypovetsky** [comment] 2020-05-16 15:40
Happened to me as well with any image. I tried different size as well

**Comment by mauhai** [comment] 2020-07-01 16:41
@aaroniker Still have the issue, was looking forward to using it.

**Comment by aaroniker** [comment] 2020-07-02 14:38
@DennisLypovetsky @mauhai for me its still working without any problems.
Do you have more information for me? Image size? OS?
Sadly cant reproduce this.

**Comment by r0binxp** [comment] 2020-08-07 17:55
I'm Trying in Windows 10 and Receive the same Error. Tested with various images.

**Comment by stefanj2** [comment] 2020-08-17 13:45
Mac OS Mojave, image size: 15MB (300 x 277), happens to me as well.

**Comment by aaroniker** [comment] 2020-08-17 23:33
> Mac OS Mojave, image size: 15MB (300 x 277), happens to me as well.

can you upload the image somewhere? will try to reproduce again

**Comment by kylemhudson** [comment] 2020-10-01 14:43
@aaroniker figured this one out. Uploaded a 6MB JPG, and it gave me the same error. (Attached). 

Sized the image down from 4000x3000 down to 2000x1500 and from 6MB down to under 1MB, and the plugin worked/ran. 

Seems like the API just has a size threshold and instead of saying "there was an error reading the file" it should read that the image is too big and give a more appropriate message "please reduce the file size to.. XXX". 

<img width="864" alt="Screen Shot 2020-10-01 at 10 43 46 AM" src="https://user-images.githubusercontent.com/14058890/94824408-fdbd7700-03d2-11eb-8685-d99dad85aca0.png">

**Comment by mauhai** [comment] 2020-10-01 15:05
Great! Does anyone have an idea what the size limit is?

**Comment by aaroniker** [comment] 2020-10-09 16:41
thanks a lot guys - will research & adjust the error message the next week :) thanks for figuring out @kylemhudson

**Comment by viznov** [comment] 2020-11-08 00:03
I second with the issue. Tried 4 pictures, 1 was a success, 3 others have failed. It doesn't seem to be size dependent. Please give me a clue how to use the plugin? The idea of the plugin is awesome, thank you!

**Comment by aaroniker** [comment] 2021-06-28 14:29
this should be fixed now

**Closed by aaroniker** 2021-06-28 14:29 UTC
